# Generated by Django 3.0.4 on 2020-05-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='catalog_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ProductForm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ProductForm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productstuff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ProductStuff'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producttopping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ProductTopping'),
        ),
    ]
