# Generated by Django 3.0.4 on 2020-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200510_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detailtext',
            field=models.CharField(max_length=350, verbose_name='Надпись'),
        ),
    ]
