# Generated by Django 2.2.12 on 2020-05-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default='', max_length=350, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
