# Generated by Django 2.2.12 on 2020-05-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_imagemodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='name',
        ),
    ]
