# Generated by Django 2.2.12 on 2020-05-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_imagemodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='name',
        ),
    ]
