# Generated by Django 2.2.12 on 2020-05-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_imagemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Имя'),
        ),
    ]
