# Generated by Django 2.2.12 on 2020-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200516_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='surname',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Фамилия'),
        ),
    ]
